spring:
  profiles:
    active: dev
---

spring:
  profiles: dev

  output:
    ansi:
      enabled: always

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:log4jdbc:mysql://13.125.196.188:3306/realestate_data?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: kim111
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

    hikari:
      pool-name: hikari-cp
      maximum-pool-size: 30
      minimum-idle: 2
  http:
    converters:
      preferred-json-mapper: jackson
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  redis:
    host: "redis"
    password: ""
    port: 6379
  data:
    redis:
      repositories:
        enabled: true
jwt:
  secret: kim111

---

spring:
  profiles: test

  output:
    ansi:
      enabled: always

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/realestate_data?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: kim111
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

    hikari:
      pool-name: hikari-cp
      maximum-pool-size: 30
      minimum-idle: 2
  http:
    converters:
      preferred-json-mapper: jackson
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  redis:
    host: 127.0.0.1
    password: ""
    port: 6379
  data:
    redis:
      repositories:
        enabled: true
  security:
    oauth2:
      resourceserver:


jwt:
  secret: kim111

#server:
#  port: 8090